import { describe, expect, it } from 'vitest';
import {
  generateCssFile,
  generateOutputs,
  generateScssFile,
  generateTailwindPreset,
} from '../../src/plugin/generators';
import { buildCssVariableMaps, modeOverrides } from '../../src/plugin/generators/cssVariables';
import { DEFAULT_EXPORT_OPTIONS } from '../../src/shared/messages';
import type { DesignSystem, VariableToken } from '../../src/shared/types';
import { makeDesignSystem } from './fixtures';

function variable(overrides: Partial<VariableToken>): VariableToken {
  return {
    id: 'v',
    name: 'Color/X',
    path: ['Color', 'X'],
    collectionId: 'c',
    collectionName: 'Theme',
    resolvedType: 'COLOR',
    category: 'color',
    description: '',
    scopes: [],
    valuesByMode: [],
    codeSyntax: {},
    cssName: '--color-x',
    usedByComponents: [],
    ...overrides,
  };
}

const float = (value: number) => ({ kind: 'float' as const, value });
const mode = (modeName: string, value: VariableToken['valuesByMode'][number]['value']) => ({
  modeId: modeName,
  modeName,
  value,
});

describe('modeOverrides', () => {
  it('keeps only values that differ from the default mode', () => {
    const maps = buildCssVariableMaps(makeDesignSystem());
    const overrides = modeOverrides(maps);
    // Light equals the default, so only Dark remains, and only for the variable that changes.
    expect(overrides).toEqual([
      { modeName: 'Dark', slug: 'dark', vars: { '--color-primary-500': '#1a3399' } },
    ]);
  });
});

describe('generateCssFile', () => {
  it('writes tokens.css with :root defaults and a [data-theme] block per extra mode', () => {
    const file = generateCssFile(makeDesignSystem());
    expect(file.path).toBe('tokens.css');
    expect(file.content).toContain(':root {\n  --color-primary-500: #3366ff;');
    expect(file.content).toContain('--semantic-color-danger: var(--color-primary-500);');
    expect(file.content).toContain('[data-theme="dark"] {\n  --color-primary-500: #1a3399;\n}');
  });

  it('adds a prefers-color-scheme rule for a dark mode unless the page opts into light', () => {
    const { content } = generateCssFile(makeDesignSystem());
    expect(content).toContain('@media (prefers-color-scheme: dark) {');
    expect(content).toContain(':root:not([data-theme="light"]) {');
  });

  it('does not emit a media query for non-dark modes', () => {
    const ds = makeDesignSystem();
    ds.variables[0].valuesByMode[1].modeName = 'High Contrast';
    const { content } = generateCssFile(ds);
    expect(content).toContain('[data-theme="high-contrast"]');
    expect(content).not.toContain('prefers-color-scheme');
  });

  it('quotes font families that are not plain identifiers', () => {
    const ds = makeDesignSystem();
    ds.styles.text[0].textProperties!.fontFamily = 'SF Pro Display';
    expect(generateCssFile(ds).content).toContain('--heading-large-font-family: "SF Pro Display";');
  });

  it('quotes FONT_FAMILY string variables', () => {
    const ds = makeDesignSystem();
    ds.variables.push(
      variable({
        id: 'ff',
        name: 'Font/Family/Body',
        path: ['Font', 'Family', 'Body'],
        resolvedType: 'STRING',
        category: 'typography',
        scopes: ['FONT_FAMILY'],
        cssName: '--font-family-body',
        valuesByMode: [mode('Light', { kind: 'string', value: 'Source Sans 3' })],
      }),
    );
    expect(generateCssFile(ds).content).toContain('--font-family-body: "Source Sans 3";');
  });

  it('produces a valid, header-only file for an empty design system', () => {
    const ds: DesignSystem = makeDesignSystem();
    ds.variables = [];
    ds.styles = { text: [], color: [], effect: [], grid: [] };
    const { content } = generateCssFile(ds);
    expect(content).toBe(
      '/* Generated by DesignMD from "Fixture File" — do not edit by hand. */\n',
    );
  });

  it('cannot be broken out of by a file name containing a comment terminator', () => {
    const ds = makeDesignSystem();
    ds.metadata.fileName = 'evil */ body { display:none } /*';
    expect(generateCssFile(ds).content.split('\n')[0].split('*/')).toHaveLength(2);
  });
});

describe('generateScssFile', () => {
  it('writes Sass variables with aliases as references', () => {
    const file = generateScssFile(makeDesignSystem());
    expect(file.path).toBe('_tokens.scss');
    expect(file.content).toContain('$color-primary-500: #3366ff;');
    expect(file.content).toContain('$semantic-color-danger: $color-primary-500;');
  });

  it('adds a $modes map with only the values that differ', () => {
    const { content } = generateScssFile(makeDesignSystem());
    expect(content).toContain('$modes: (');
    expect(content).toContain('"dark": (\n    "color-primary-500": #1a3399,');
    expect(content).not.toContain('"light"');
  });

  it('prefixes names that would start with a digit', () => {
    const ds = makeDesignSystem();
    ds.variables.push(
      variable({
        id: 'x',
        name: '2xl',
        path: ['2xl'],
        resolvedType: 'FLOAT',
        category: 'spacing',
        cssName: '--2xl',
        valuesByMode: [mode('Light', float(40))],
      }),
    );
    expect(generateScssFile(ds).content).toContain('$_2xl: 40px;');
  });

  it('omits $modes when no mode differs', () => {
    const ds = makeDesignSystem();
    ds.variables.forEach((v) => (v.valuesByMode = v.valuesByMode.slice(0, 1)));
    expect(generateScssFile(ds).content).not.toContain('$modes');
  });
});

describe('generateTailwindPreset', () => {
  type Loaded = {
    extend: Record<string, Record<string, unknown>>;
    base: Record<string, Record<string, unknown>> | undefined;
  };

  /** Evaluates the preset with a stub for tailwindcss/plugin and returns theme.extend + addBase input. */
  function load(ds: DesignSystem): Loaded {
    const module = {
      exports: {} as {
        theme: { extend: Loaded['extend'] };
        plugins?: Array<{ handler: (api: { addBase: (b: unknown) => void }) => void }>;
      },
    };
    const fakeRequire = (name: string) => {
      if (name !== 'tailwindcss/plugin') throw new Error(`unexpected require(${name})`);
      return (handler: unknown) => ({ handler });
    };
    new Function('module', 'require', generateTailwindPreset(ds).content)(module, fakeRequire);
    let base: Loaded['base'];
    module.exports.plugins?.[0].handler({ addBase: (b) => (base = b as Loaded['base']) });
    return { extend: module.exports.theme.extend, base };
  }

  it('is loadable CommonJS exposing theme.extend', () => {
    const { extend } = load(makeDesignSystem());
    expect(extend).toBeDefined();
    expect(generateTailwindPreset(makeDesignSystem()).path).toBe('tailwind.tokens.js');
  });

  it('references CSS variables for colors, dropping redundant bucket prefixes', () => {
    const { colors } = load(makeDesignSystem()).extend;
    expect(colors).toEqual({
      primary: { '500': 'rgb(var(--color-primary-500-rgb) / <alpha-value>)' },
      danger: 'rgb(var(--semantic-color-danger-rgb) / <alpha-value>)',
    });
  });

  it('maps text styles to fontSize tuples and effect styles to boxShadow', () => {
    const { fontSize, boxShadow } = load(makeDesignSystem()).extend;
    expect(fontSize['heading-large']).toEqual([
      'var(--heading-large-font-size)',
      {
        lineHeight: 'var(--heading-large-line-height)',
        letterSpacing: 'var(--heading-large-letter-spacing)',
        fontWeight: 'var(--heading-large-font-weight)',
      },
    ]);
    expect(boxShadow).toEqual({ card: 'var(--elevation-card)' });
  });

  it('splits spacing variables into spacing and borderRadius', () => {
    const ds = makeDesignSystem();
    ds.variables.push(
      variable({
        id: 's',
        name: 'Spacing/md',
        path: ['Spacing', 'md'],
        resolvedType: 'FLOAT',
        category: 'spacing',
        cssName: '--spacing-md',
        valuesByMode: [mode('Light', float(16))],
      }),
      variable({
        id: 'r',
        name: 'Radius/lg',
        path: ['Radius', 'lg'],
        resolvedType: 'FLOAT',
        category: 'spacing',
        scopes: ['CORNER_RADIUS'],
        cssName: '--radius-lg',
        valuesByMode: [mode('Light', float(12))],
      }),
    );
    const { extend } = load(ds);
    expect(extend.spacing).toEqual({ md: 'var(--spacing-md)' });
    expect(extend.borderRadius).toEqual({ lg: 'var(--radius-lg)' });
  });

  it('only references variables that exist in tokens.css and omits empty groups', () => {
    const ds = makeDesignSystem();
    ds.variables = [];
    ds.styles.effect = [];
    ds.styles.text = [];
    const { extend } = load(ds);
    // Only the Surface/Background color style remains.
    expect(extend.colors).toEqual({
      surface: { background: 'rgb(var(--surface-background-rgb) / <alpha-value>)' },
    });
    expect(Object.keys(extend)).toEqual(['colors']);
  });
});

describe('generateTailwindPreset opacity support', () => {
  const evaluate = (ds: DesignSystem) => {
    const module = {
      exports: {} as {
        plugins?: Array<{ handler: (api: { addBase: (b: unknown) => void }) => void }>;
      },
    };
    new Function('module', 'require', generateTailwindPreset(ds).content)(
      module,
      () => (handler: unknown) => ({ handler }),
    );
    let base: Record<string, Record<string, unknown>> | undefined;
    module.exports.plugins?.[0].handler({ addBase: (b) => (base = b as typeof base) });
    return base;
  };

  it('defines RGB channels for opaque colors, with aliases pointing at the target channels', () => {
    const base = evaluate(makeDesignSystem())!;
    expect(base[':root']).toEqual({
      '--color-primary-500-rgb': '51 102 255',
      '--semantic-color-danger-rgb': 'var(--color-primary-500-rgb)',
    });
  });

  it('overrides channels per mode and mirrors dark mode in a prefers-color-scheme rule', () => {
    const base = evaluate(makeDesignSystem())!;
    expect(base['[data-theme="dark"]']).toEqual({ '--color-primary-500-rgb': '26 51 153' });
    expect(base['@media (prefers-color-scheme: dark)']).toEqual({
      ':root:not([data-theme="light"])': { '--color-primary-500-rgb': '26 51 153' },
    });
  });

  it('leaves translucent colors as plain var() references without channels', () => {
    const ds = makeDesignSystem();
    ds.variables.push(
      variable({
        id: 'o',
        name: 'Color/Overlay',
        path: ['Color', 'Overlay'],
        cssName: '--color-overlay',
        valuesByMode: [
          mode('Light', { kind: 'color', color: { hex: '#00000080', r: 0, g: 0, b: 0, a: 0.5 } }),
        ],
      }),
    );
    const content = generateTailwindPreset(ds).content;
    expect(content).toContain('"overlay": "var(--color-overlay)"');
    expect(content).not.toContain('--color-overlay-rgb');
  });

  it('omits the plugin entirely when there are no opaque colors', () => {
    const ds = makeDesignSystem();
    ds.variables = [];
    ds.styles.color = [];
    const { content } = generateTailwindPreset(ds);
    expect(content).not.toContain('tailwindcss/plugin');
    expect(content).not.toContain('plugins');
  });
});

describe('generateOutputs with code outputs', () => {
  it('is opt-in: none of the new files are in the default selection', () => {
    expect(DEFAULT_EXPORT_OPTIONS.cssFile).toBe(false);
    expect(DEFAULT_EXPORT_OPTIONS.scssFile).toBe(false);
    expect(DEFAULT_EXPORT_OPTIONS.tailwindPreset).toBe(false);
    const paths = generateOutputs(makeDesignSystem(), DEFAULT_EXPORT_OPTIONS).map((f) => f.path);
    expect(paths).not.toContain('tokens.css');
  });

  it('adds each selected file', () => {
    const paths = generateOutputs(makeDesignSystem(), {
      ...DEFAULT_EXPORT_OPTIONS,
      designMd: false,
      componentDocs: false,
      cssFile: true,
      scssFile: true,
      tailwindPreset: true,
    }).map((f) => f.path);
    expect(paths).toEqual(['tokens.css', '_tokens.scss', 'tailwind.tokens.js']);
  });
});
