import type { DesignSystem } from '@shared/types';
import type { GeneratedFile } from '@shared/messages';
import { buildCssVariableMaps, modeOverrides } from './cssVariables';

function block(selector: string, vars: Record<string, string>, indent = ''): string {
  const lines = Object.entries(vars).map(([name, value]) => `${indent}  ${name}: ${value};`);
  return `${indent}${selector} {\n${lines.join('\n')}\n${indent}}`;
}

/**
 * tokens.css: every variable as a CSS custom property on :root (default mode), plus one
 * `[data-theme="<mode>"]` block per additional mode. A mode named "dark" also gets a
 * prefers-color-scheme rule so it applies automatically unless the page opts into light.
 */
export function generateCssFile(ds: DesignSystem): GeneratedFile {
  const maps = buildCssVariableMaps(ds);
  const sections: string[] = [
    `/* Generated by DesignMD from "${ds.metadata.fileName.replace(/\*\//g, '* /')}" — do not edit by hand. */`,
  ];

  if (Object.keys(maps.root).length > 0) sections.push(block(':root', maps.root));

  for (const { modeName, slug, vars } of modeOverrides(maps)) {
    sections.push(
      `/* Mode: ${modeName.replace(/\*\//g, '* /')} */\n${block(`[data-theme="${slug}"]`, vars)}`,
    );
    if (slug === 'dark') {
      sections.push(
        `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', vars, '  ')}\n}`,
      );
    }
  }

  return { path: 'tokens.css', content: sections.join('\n\n') + '\n' };
}
