import type { DesignSystem } from '@shared/types';
import type { GeneratedFile } from '@shared/messages';
import { buildCssVariableMaps, modeOverrides } from './cssVariables';

/** "--color-primary-500" -> "color-primary-500"; Sass identifiers can't start with a digit. */
function scssName(cssName: string): string {
  const name = cssName.replace(/^--/, '');
  return /^\d/.test(name) ? `_${name}` : name;
}

/** Aliases become references to the other Sass variable: var(--a) -> $a. */
function scssValue(value: string): string {
  const alias = /^var\((--[^)]+)\)$/.exec(value);
  return alias ? `$${scssName(alias[1])}` : value;
}

/**
 * _tokens.scss: default-mode values as Sass variables (aliases kept as references), plus a
 * `$modes` map holding only what differs in each additional mode.
 */
export function generateScssFile(ds: DesignSystem): GeneratedFile {
  const maps = buildCssVariableMaps(ds);
  const lines = [
    `// Generated by DesignMD from "${ds.metadata.fileName.replace(/\n/g, ' ')}" — do not edit by hand.`,
  ];

  const variables = Object.entries(maps.root).map(
    ([name, value]) => `$${scssName(name)}: ${scssValue(value)};`,
  );
  if (variables.length > 0) lines.push('', ...variables);

  const overrides = modeOverrides(maps);
  if (overrides.length > 0) {
    lines.push('', '// Values that differ from the default mode, per mode.', '$modes: (');
    for (const { modeName, slug, vars } of overrides) {
      lines.push(`  // ${modeName.replace(/\n/g, ' ')}`, `  "${slug}": (`);
      for (const [name, value] of Object.entries(vars)) {
        lines.push(`    "${scssName(name)}": ${scssValue(value)},`);
      }
      lines.push('  ),');
    }
    lines.push(');');
  }

  return { path: '_tokens.scss', content: lines.join('\n') + '\n' };
}
