import type { ComponentDocumentation, ComponentAPIProperty } from '../types';
import type { FoundationsSchema } from '@/types/schemas';
import type { IconLibraryData } from './icon-utils';
import {
  inferComponentIntent,
  inferInteractionBehaviors,
  inferResponsiveBehavior,
  generateUXRules,
  generateAccessibilityObservations,
  inferSemanticLayerName,
} from '../../inference/semantic-inference';
import { buildTokenTableRows } from '../../inference/token-resolver';

function escapeMarkdown(text: string | undefined | null): string {
  if (!text) return '—';
  return String(text).replace(/[|]/g, '\\|');
}

function normalizeComponentName(name: string | undefined): string {
  if (!name) return '—';
  return name.replace(/\//g, ' – ');
}

function slugify(name: string | undefined): string {
  if (!name) return '';
  return name
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function formatTokenBinding(value: string | undefined): string {
  if (!value) return '—';
  // Value should be either the actual variable name (from the map) or "var(id)" fallback
  return value;
}

function buildComponentAPI(components: ComponentDocumentation[]): ComponentAPIProperty[] {
  const api: ComponentAPIProperty[] = [];
  const props = new Map<string, Set<string>>();

  // Collect all unique property values across all variants
  components.forEach((comp) => {
    comp.properties.forEach((prop) => {
      if (!props.has(prop.name)) {
        props.set(prop.name, new Set(prop.values));
      } else {
        prop.values.forEach((v) => props.get(prop.name)!.add(v));
      }
    });
  });

  // Build API properties
  props.forEach((values, name) => {
    const valueList = Array.from(values).sort().join(', ');
    api.push({
      property: name,
      type: 'enum', // Simplified - all variant properties are treated as enums
      values: valueList,
      required: 'No',
    });
  });

  return api.sort((a, b) => a.property.localeCompare(b.property));
}

export function generateMarkdown(
  components: ComponentDocumentation[],
  foundations?: FoundationsSchema,
  includeFoundations: boolean = false,
  iconLibrary?: IconLibraryData
): string {
  const parts: string[] = [];

  // ─── Page grouping (for full-system: each Figma page = one component category) ──
  // Build once, used in both overview counts and summary table
  const pageGroupsMap = new Map<string, ComponentDocumentation[]>();
  components.forEach((comp) => {
    const page = comp.pageName || 'Uncategorized';
    if (!pageGroupsMap.has(page)) pageGroupsMap.set(page, []);
    pageGroupsMap.get(page)!.push(comp);
  });
  const pageGroups = Array.from(pageGroupsMap.entries()).sort(([a], [b]) => a.localeCompare(b));
  // The authoritative component count: number of distinct design component pages
  // (each page in a well-structured design system = one component family)
  const componentCount = includeFoundations && pageGroups.length > 0 ? pageGroups.length : components.length;

  // ─── Document Header & Metadata ───────────────────────────────────────
  const title = includeFoundations ? 'Design System Documentation' : (components.length === 1 ? `${components[0]?.name} Component` : 'Components Documentation');
  parts.push(`# ${title}\n`);
  parts.push(`> Generated by Documint · ${new Date().toLocaleDateString()}\n`);
  parts.push('---\n');

  // ─── Overview Section (only for full system) ───────────────────────────
  if (includeFoundations) {
    parts.push('## 1. Overview\n');
    parts.push('### 1.1 Structure Breakdown\n');

    // Foundations breakdown
    if (foundations) {
      const hasColors = (foundations.colors?.length || 0) > 0;
      const hasTypography = (foundations.typography?.length || 0) > 0;
      const hasSpacing = (foundations.spacing?.length || 0) > 0;
      const hasGrids = (foundations.grids?.length || 0) > 0;

      if (hasColors || hasTypography || hasSpacing || hasGrids) {
        parts.push('- **Foundations**');
        if (hasColors) parts.push(`  - Colors: ${foundations.colors?.length || 0} tokens`);
        if (hasTypography) parts.push(`  - Typography: ${foundations.typography?.length || 0} tokens`);
        if (hasSpacing) parts.push(`  - Spacing: ${foundations.spacing?.length || 0} tokens`);
        if (hasGrids) parts.push(`  - Grids: ${foundations.grids?.length || 0} definitions`);
      }
    }

    // Debug: log page grouping info
    console.log(`generateMarkdown - ${components.length} component sets across ${componentCount} pages:`, pageGroups.map(([p, cs]) => `${p}(${cs.length})`).join(', '));

    // Components breakdown — grouped by page
    parts.push(`- **Components** (${componentCount} total)`);
    pageGroups.slice(0, 10).forEach(([pageName, pageComps]) => {
      const setCount = pageComps.length;
      const sets = setCount > 1 ? ` · ${setCount} component sets` : '';
      parts.push(`  - ${escapeMarkdown(pageName)}${sets}`);
    });
    if (pageGroups.length > 10) {
      parts.push(`  - ... and ${pageGroups.length - 10} more`);
    }

    // Icon Library breakdown
    if (iconLibrary) {
      parts.push(`- **Icon Library** (${iconLibrary.totalIcons} icons)`);
      iconLibrary.groups.slice(0, 5).forEach((group) => {
        parts.push(`  - ${escapeMarkdown(group.name)}: ${group.count} icons`);
      });
      if (iconLibrary.groups.length > 5) {
        parts.push(`  - ... and ${iconLibrary.groups.length - 5} more categories`);
      }
    }

    parts.push('\n');
    parts.push('---\n');

    // Metadata table
    parts.push('## 2. Metadata\n');
    parts.push('| Property | Value |');
    parts.push('|---|---|');
    parts.push(`| Generated At | ${new Date().toISOString()} |`);
    parts.push(`| Components | ${componentCount} |`);
    parts.push(`| Component Sets | ${components.length} |`);
    if (iconLibrary) {
      parts.push(`| Icons | ${iconLibrary.totalIcons} |`);
    }
    const totalVariants = components.reduce((sum, c) => sum + c.variantGroups.length, 0);
    parts.push(`| Total Variant Groups | ${totalVariants} |`);
    if (foundations) {
      parts.push(`| Total Color Tokens | ${foundations.colors?.length || 0} |`);
      parts.push(`| Total Typography Tokens | ${foundations.typography?.length || 0} |`);
      parts.push(`| Total Spacing Tokens | ${foundations.spacing?.length || 0} |`);
    }
    parts.push(`| Plugin Version | 1.0.0 |`);
    parts.push('');

    parts.push('---\n');
  }

  // ─── Foundations Section ──────────────────────────────────────────────
  if (foundations && includeFoundations) {
    parts.push('## 3. Foundations\n');

    if ((foundations.colors?.length || 0) > 0) {
      parts.push('### 3.1 Color Tokens\n');
      parts.push('| Name | Value | Type |');
      parts.push('|---|---|---|');
      foundations.colors?.forEach((color: any) => {
        const colorValue = typeof color.value === 'object' ? (color.value?.hex || color.value?.toString() || '—') : (color.value || '—');
        const colorName = color.tokenName || color.name || '—';
        parts.push(`| ${escapeMarkdown(colorName)} | ${escapeMarkdown(colorValue)} | ${color.type || '—'} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.typography?.length || 0) > 0) {
      parts.push('### 3.2 Typography Tokens\n');
      parts.push('| Name | Font Family | Size | Weight | Line Height |');
      parts.push('|---|---|---|---|---|');
      foundations.typography?.forEach((typo: any) => {
        const fontFamily = typo.fontFamily || '—';
        const fontSize = typo.fontSize || '—';
        const fontWeight = typo.fontWeight || '—';
        let lineHeight = typeof typo.lineHeight === 'object' ? (typo.lineHeight?.value || '—') : (typo.lineHeight || '—');
        // Round line height to whole number
        if (lineHeight !== '—' && !isNaN(lineHeight)) {
          lineHeight = String(Math.round(Number(lineHeight)));
        }
        const typoName = typo.tokenName || typo.name || '—';
        parts.push(`| ${escapeMarkdown(typoName)} | ${escapeMarkdown(fontFamily)} | ${escapeMarkdown(fontSize)} | ${escapeMarkdown(fontWeight)} | ${escapeMarkdown(lineHeight)} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    // Icon Library (moved below Typography)
    if (iconLibrary && iconLibrary.groups.length > 0) {
      parts.push('### 3.3 Icon Library\n');
      parts.push(`Total Icons: **${iconLibrary.totalIcons}** organized in **${iconLibrary.groups.length}** categories\n`);
      parts.push('| Category | Count | Examples |');
      parts.push('|---|---|---|');
      iconLibrary.groups.forEach((group) => {
        const examplesText = group.icons.slice(0, 3).map(icon => escapeMarkdown(icon.name || '?')).join(', ');
        const moreText = group.count > 3 ? `, ... +${group.count - 3} more` : '';
        parts.push(`| ${escapeMarkdown(group.name)} | ${group.count} | ${examplesText}${moreText} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.spacing?.length || 0) > 0) {
      parts.push('### 3.4 Spacing Tokens\n');
      parts.push('| Name | Value |');
      parts.push('|---|---|');
      foundations.spacing?.forEach((spacing: any) => {
        const spacingValue = typeof spacing.value === 'object' ? (spacing.value?.value || spacing.value?.toString() || '—') : (spacing.value || '—');
        const spacingName = spacing.tokenName || spacing.name || '—';
        parts.push(`| ${escapeMarkdown(spacingName)} | ${escapeMarkdown(spacingValue)} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.borderRadius?.length || 0) > 0) {
      parts.push('### 3.5 Border Radius Tokens\n');
      parts.push('| Name | Value | Usage |');
      parts.push('|---|---|---|');
      foundations.borderRadius?.forEach((radius: any) => {
        const radiusValue = typeof radius.value === 'object' ? (radius.value?.value || radius.value?.toString() || '—') : (radius.value || '—');
        const radiusName = radius.tokenName || radius.name || '—';
        parts.push(`| ${escapeMarkdown(radiusName)} | ${escapeMarkdown(String(radiusValue))}px | ${escapeMarkdown(radius.usageHint || '—')} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.borderWidth?.length || 0) > 0) {
      parts.push('### 3.6 Border Width Tokens\n');
      parts.push('| Name | Value | Usage |');
      parts.push('|---|---|---|');
      foundations.borderWidth?.forEach((width: any) => {
        const widthValue = typeof width.value === 'object' ? (width.value?.value || width.value?.toString() || '—') : (width.value || '—');
        const widthName = width.tokenName || width.name || '—';
        parts.push(`| ${escapeMarkdown(widthName)} | ${escapeMarkdown(String(widthValue))}px | ${escapeMarkdown(width.usageHint || '—')} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.elevation?.length || 0) > 0) {
      parts.push('### 3.7 Elevation / Shadows\n');
      parts.push('| Name | Shadow Value | Usage |');
      parts.push('|---|---|---|');
      foundations.elevation?.forEach((elev: any) => {
        const elevName = elev.tokenName || elev.name || '—';
        parts.push(`| ${escapeMarkdown(elevName)} | \`${escapeMarkdown(elev.shadowValue || '—')}\` | ${escapeMarkdown(elev.usageHint || '—')} |`);
      });
      parts.push('');
      parts.push('---\n');
    }

    if ((foundations.grids?.length || 0) > 0) {
      parts.push('### 3.8 Grid Definitions\n');
      parts.push('| Name | Columns | Gutter | Margin |');
      parts.push('|---|---|---|---|');
      foundations.grids?.forEach((grid: any) => {
        const columns = grid.columns || '—';
        const gutter = grid.gutter || '—';
        const margin = grid.margin || '—';
        const gridName = grid.tokenName || grid.name || '—';
        parts.push(`| ${escapeMarkdown(gridName)} | ${escapeMarkdown(String(columns))} | ${escapeMarkdown(String(gutter))} | ${escapeMarkdown(String(margin))} |`);
      });
      parts.push('');
      parts.push('---\n');
    }
  }

  // ─── Design Voice & Brand Section ────────────────────────────────────
  if (includeFoundations) {
    parts.push('## 4. Design Voice & Brand\n');
    parts.push('### 4.1 Voice & Tone\n');
    parts.push('Define the personality and communication style of the design system. Consider tone, vocabulary, and interaction language.\n');
    parts.push('- **Primary Tone:** [To be documented - e.g., Professional, Friendly, Authoritative]\n');
    parts.push('- **Key Principles:** [To be documented - e.g., Clear, Helpful, Trustworthy]\n');
    parts.push('- **Language Guidelines:** [To be documented]\n');
    parts.push('');

    parts.push('### 4.2 Brand Guidelines\n');
    parts.push('Core brand principles and visual identity standards.\n');
    parts.push('- **Brand Values:** [To be documented]\n');
    parts.push('- **Visual Principles:** [To be documented]\n');
    parts.push('- **Usage Guidelines:** [To be documented]\n');
    parts.push('');
    parts.push('---\n');
  }

  parts.push('## 5. Components\n\n');

  // ─── Components Summary ────────────────────────────────────────────
  if (components.length > 0) {
    parts.push('### 5.1 Summary\n');

    if (includeFoundations && pageGroups.length > 0) {
      // Full-system mode: group by page (each page = one component category)
      parts.push('| Component | Component Sets | Description |');
      parts.push('|---|---|---|');
      pageGroups.forEach(([pageName, pageComps]) => {
        const setNames = pageComps.map((c) => escapeMarkdown(c.name)).join(', ');
        const description = pageComps[0]?.description || '—';
        const descSnippet = escapeMarkdown(description.substring(0, 50)) + (description.length > 50 ? '...' : '');
        parts.push(`| **${escapeMarkdown(pageName)}** | ${setNames} | ${descSnippet} |`);
      });
    } else {
      // Selected / current-page mode: list components individually
      parts.push('| Component | Description | Variants |');
      parts.push('|---|---|---|');
      components.forEach((comp) => {
        const variantCount = comp.variantGroups?.length || 0;
        const description = comp.description || '—';
        parts.push(`| ${escapeMarkdown(comp.name)} | ${escapeMarkdown(description.substring(0, 50))}${description.length > 50 ? '...' : ''} | ${variantCount} |`);
      });
    }

    parts.push('');
    parts.push('---\n\n');
  }

  // ─── Per-Component Sections ────────────────────────────────────────────

  components.forEach((comp, index) => {
    if (index > 0) {
      parts.push('\n---\n');
    }

    const normalizedName = normalizeComponentName(comp.name);
    const slug = slugify(comp.name);

    // HTML comment markers for AI/MCP parsing
    const intent =
      comp.intent ||
      inferComponentIntent(comp.name, comp.category || '', comp.variantGroups, comp.states);
    const interactionBehaviors =
      comp.interactionBehaviors ||
      inferInteractionBehaviors(comp.name, comp.category || '', comp.states);

    parts.push(`<!-- COMPONENT_ID: ${slug} -->`);
    parts.push(`<!-- SEMANTIC_ROLE: ${slugify(intent)} -->`);
    parts.push(`<!-- INTERACTION_TYPE: ${interactionBehaviors.map((b) => slugify(b.behavior)).join(',') || 'none'} -->\n`);

    // Component heading
    parts.push(`# ${normalizedName}\n`);

    // ─── Description ───────────────────────────────────────────────────

    parts.push('## Description\n');
    if (comp.description && comp.description.trim()) {
      parts.push(`${comp.description}\n`);
    } else {
      parts.push('No description provided.\n');
    }

    // ─── Intent ────────────────────────────────────────────────────────

    parts.push('## Intent\n');
    parts.push(`${intent}\n`);

    // ─── Component Relationships ────────────────────────────────────────

    if (comp.anatomy && comp.anatomy.length > 0) {
      parts.push('## Component Relationships\n');
      parts.push('| Relationship | Component |');
      parts.push('|---|---|');
      comp.anatomy.forEach((part) => {
        parts.push(`| Contains | ${escapeMarkdown(part.name)} |`);
      });
      parts.push('');
    }

    // ─── Anatomy ────────────────────────────────────────────────────────

    if (comp.anatomy && comp.anatomy.length > 0) {
      parts.push('## Anatomy\n');
      parts.push('| Part | Role | Description |');
      parts.push('|---|---|---|');
      comp.anatomy.forEach((part) => {
        const role = inferSemanticLayerName(part.name);
        parts.push(`| ${escapeMarkdown(part.name)} | ${role} | ${escapeMarkdown(part.description)} |`);
      });
      parts.push('');
    }

    // ─── Variants ──────────────────────────────────────────────────────

    if (comp.variantGroups && comp.variantGroups.length > 0) {
      parts.push('## Variants\n');

      parts.push('### Variant Groups\n');
      parts.push('| Group |');
      parts.push('|---|');
      comp.variantGroups.forEach((group) => {
        parts.push(`| ${escapeMarkdown(group.name)} |`);
      });
      parts.push('');

      parts.push('### Variant Values\n');
      parts.push('| Group | Values |');
      parts.push('|---|---|');
      comp.variantGroups.forEach((group) => {
        const values = group.values.join(', ');
        parts.push(`| ${escapeMarkdown(group.name)} | ${escapeMarkdown(values)} |`);
      });
      parts.push('');
    }

    // ─── States ────────────────────────────────────────────────────────

    if (comp.states && comp.states.length > 0) {
      parts.push('## States\n');
      parts.push('| State | Description |');
      parts.push('|---|---|');
      comp.states.forEach((state) => {
        parts.push(`| ${escapeMarkdown(state.name)} | ${escapeMarkdown(state.description)} |`);
      });
      parts.push('');
    }

    // ─── Properties ────────────────────────────────────────────────────

    if (comp.properties && comp.properties.length > 0) {
      parts.push('## Properties\n');
      parts.push('| Property | Values |');
      parts.push('|---|---|');
      comp.properties.forEach((prop) => {
        const values = prop.values.join(', ');
        parts.push(`| ${escapeMarkdown(prop.name)} | ${escapeMarkdown(values)} |`);
      });
      parts.push('');
    }

    // ─── Component API ─────────────────────────────────────────────────

    const api = comp.componentAPI || buildComponentAPI([comp]);
    if (api && api.length > 0) {
      parts.push('## Component API\n');
      parts.push('<!-- COMPONENT_API_START -->');
      parts.push('| Property | Type | Values | Required |');
      parts.push('|---|---|---|---|');
      api.forEach((prop) => {
        parts.push(
          `| ${escapeMarkdown(prop.property)} | ${escapeMarkdown(prop.type)} | ${escapeMarkdown(prop.values)} | ${escapeMarkdown(prop.required)} |`
        );
      });
      parts.push('<!-- COMPONENT_API_END -->');
      parts.push('');
    }

    // ─── Layout Specifications ─────────────────────────────────────────

    if (comp.layoutProperties) {
      const layout = comp.layoutProperties;
      parts.push('## Layout Specifications\n');

      // Padding & Spacing
      if (layout.autoLayout?.padding) {
        const p = layout.autoLayout.padding;
        parts.push('### Padding & Spacing\n');
        parts.push('| Property | Value |');
        parts.push('|---|---|');
        parts.push(`| Padding Top | ${p.top}px |`);
        parts.push(`| Padding Right | ${p.right}px |`);
        parts.push(`| Padding Bottom | ${p.bottom}px |`);
        parts.push(`| Padding Left | ${p.left}px |`);
        if (layout.autoLayout.spacing !== undefined) {
          parts.push(`| Gap/Spacing | ${layout.autoLayout.spacing}px |`);
        }
        parts.push('');
      }

      // Layout Behavior
      if (layout.autoLayout) {
        const al = layout.autoLayout;
        parts.push('### Layout Behavior\n');
        parts.push('| Property | Value |');
        parts.push('|---|---|');
        parts.push(`| Type | Auto Layout (${al.direction === 'HORIZONTAL' ? 'Row' : 'Column'}) |`);
        if (al.alignment) parts.push(`| Alignment | ${al.alignment} |`);
        if (al.justifyContent) parts.push(`| Justify Content | ${al.justifyContent} |`);
        parts.push('');
      }

      // Sizing
      if (layout.dimensions?.width || layout.dimensions?.height) {
        parts.push('### Sizing\n');
        parts.push('| Property | Value |');
        parts.push('|---|---|');
        if (layout.dimensions?.width) parts.push(`| Width | ${layout.dimensions.width}px |`);
        if (layout.dimensions?.height) parts.push(`| Height | ${layout.dimensions.height}px |`);
        parts.push('');
      }

      // Positioning
      if (layout.constraints) {
        const c = layout.constraints;
        parts.push('### Positioning\n');
        parts.push('| Property | Value |');
        parts.push('|---|---|');
        parts.push(`| Horizontal Constraint | ${c.horizontal} |`);
        parts.push(`| Vertical Constraint | ${c.vertical} |`);
        parts.push('');
      }

      // Responsive Behavior
      const responsiveBehavior = comp.responsiveBehavior || inferResponsiveBehavior(layout);
      if (responsiveBehavior && responsiveBehavior.length > 0) {
        parts.push('### Responsive Behavior\n');
        responsiveBehavior.forEach((behavior) => {
          parts.push(`- ${behavior}`);
        });
        parts.push('');
      }
    }

    // ─── Interaction Behavior ──────────────────────────────────────────

    if (interactionBehaviors && interactionBehaviors.length > 0) {
      parts.push('## Interaction Behavior\n');
      parts.push('| Behavior | Description |');
      parts.push('|---|---|');
      interactionBehaviors.forEach((behavior) => {
        parts.push(`| ${escapeMarkdown(behavior.behavior)} | ${escapeMarkdown(behavior.description)} |`);
      });
      parts.push('');
    }

    // ─── Token Bindings ────────────────────────────────────────────────

    const hasBindings =
      (comp.tokenBindings?.colors?.length || 0) > 0 ||
      (comp.tokenBindings?.spacing?.length || 0) > 0 ||
      (comp.tokenBindings?.typography?.length || 0) > 0;

    if (hasBindings) {
      parts.push('## Token Bindings\n');
      parts.push('<!-- TOKEN_BINDINGS_START -->');

      // Colors
      if (comp.tokenBindings?.colors && comp.tokenBindings.colors.length > 0) {
        parts.push('### Colors\n');
        parts.push('| Element | Token |');
        parts.push('|---|---|');
        comp.tokenBindings.colors.forEach((binding) => {
          parts.push(`| ${escapeMarkdown(binding.element)} | ${escapeMarkdown(formatTokenBinding(binding.value))} |`);
        });
        parts.push('');
      }

      // Typography
      if (comp.tokenBindings?.typography && comp.tokenBindings.typography.length > 0) {
        parts.push('### Typography\n');
        parts.push('| Element | Token |');
        parts.push('|---|---|');
        comp.tokenBindings.typography.forEach((binding) => {
          parts.push(`| ${escapeMarkdown(binding.element)} | ${escapeMarkdown(formatTokenBinding(binding.value))} |`);
        });
        parts.push('');
      }

      // Spacing
      if (comp.tokenBindings?.spacing && comp.tokenBindings.spacing.length > 0) {
        parts.push('### Spacing\n');
        parts.push('| Element | Token |');
        parts.push('|---|---|');
        comp.tokenBindings.spacing.forEach((binding) => {
          parts.push(`| ${escapeMarkdown(binding.element)} | ${escapeMarkdown(formatTokenBinding(binding.value))} |`);
        });
        parts.push('');
      }

      parts.push('<!-- TOKEN_BINDINGS_END -->');
    }

    // ─── Accessibility Notes ───────────────────────────────────────────

    const a11yObservations =
      comp.accessibilityObservations || generateAccessibilityObservations(comp.category || '', comp.states, comp.layoutProperties, comp.anatomy);

    if (a11yObservations && a11yObservations.length > 0) {
      parts.push('## Accessibility Notes\n');
      a11yObservations.forEach((obs) => {
        parts.push(`- ${obs}`);
      });
      parts.push('');
    }

    // ─── Usage Guidelines ──────────────────────────────────────────────

    parts.push('## Usage Guidelines\n');

    if (comp.usage.whenToUse && comp.usage.whenToUse.length > 0) {
      parts.push('### When to use\n');
      comp.usage.whenToUse.forEach((guideline) => {
        parts.push(`- ${guideline}`);
      });
      parts.push('');
    }

    if (comp.usage.whenNotToUse && comp.usage.whenNotToUse.length > 0) {
      parts.push('### When not to use\n');
      comp.usage.whenNotToUse.forEach((guideline) => {
        parts.push(`- ${guideline}`);
      });
      parts.push('');
    }

    if (comp.usage.dos && comp.usage.dos.length > 0) {
      parts.push('### Do\n');
      comp.usage.dos.forEach((guideline) => {
        parts.push(`- ${guideline}`);
      });
      parts.push('');
    }

    if (comp.usage.donts && comp.usage.donts.length > 0) {
      parts.push('### Don\'t\n');
      comp.usage.donts.forEach((guideline) => {
        parts.push(`- ${guideline}`);
      });
      parts.push('');
    }

    // ─── UX Rules ──────────────────────────────────────────────────────

    const uxRules = comp.uxRules || generateUXRules(comp.name, comp.category || '', comp.states, comp.anatomy);

    if (uxRules && uxRules.length > 0) {
      parts.push('## UX Rules\n');
      uxRules.forEach((rule) => {
        parts.push(`- ${rule}`);
      });
      parts.push('');
    }

    // ─── Assumptions Made ──────────────────────────────────────────────

    if (comp.assumptions && comp.assumptions.length > 0) {
      parts.push('## Assumptions Made\n');
      parts.push('| Category | Description |');
      parts.push('|---|---|');
      comp.assumptions.forEach((assumption) => {
        parts.push(`| ${escapeMarkdown(assumption.category)} | ${escapeMarkdown(assumption.description)} |`);
      });
      parts.push('');
    }

    // ─── Anti-patterns ─────────────────────────────────────────────────

    parts.push('## Anti-patterns\n');
    parts.push('Common mistakes to avoid when using this component:\n');
    parts.push(`- Don't use for unrelated purposes\n`);
    parts.push(`- Avoid combining incompatible states\n`);
    parts.push(`- Don't override token bindings arbitrarily\n`);
    parts.push('');
  });

  // ─── Component Anti-patterns Section ────────────────────────────────────

  if (components.length > 0) {
    parts.push('\n---\n');
    parts.push('## 6. Component Anti-patterns\n');
    parts.push('Common patterns to avoid across all components:\n');
    parts.push('- **Over-customization:** Avoid creating too many variants for edge cases\n');
    parts.push('- **Inconsistent naming:** Keep component names aligned with design system vocabulary\n');
    parts.push('- **Missing documentation:** Always document component intent and usage\n');
    parts.push('- **Orphaned components:** Remove unused components to maintain clarity\n');
    parts.push('- **Inconsistent behavior:** Ensure similar components behave predictably\n');
    parts.push('- **Token misuse:** Use semantic tokens instead of hardcoded values\n');
    parts.push('');
  }

  // ─── Component Prompts Section ────────────────────────────────────────

  if (components.length > 0) {
    parts.push('\n---\n');
    parts.push('## 7. Component Usage Examples\n');
    parts.push('Example usage scenarios and recommended approaches for each component:\n');

    components.slice(0, 15).forEach((comp) => {
      const variantCount = comp.variantGroups?.length || 0;
      const variants = variantCount > 0 ? ` with ${variantCount} variant${variantCount > 1 ? 's' : ''}` : '';
      parts.push(`- **${escapeMarkdown(comp.name)}**${variants}: ${escapeMarkdown(comp.description?.substring(0, 80) || 'Use for primary component functionality')}`);
    });
    if (components.length > 15) {
      parts.push(`- ... and ${components.length - 15} more components`);
    }
    parts.push('');
  }

  // ─── Known Gaps Section ────────────────────────────────────────────────

  parts.push('\n---\n');
  parts.push('## 8. Known Gaps & Recommendations\n');
  parts.push('Areas for improvement in the design system:\n');
  parts.push('- [ ] Document responsive breakpoints and mobile-first approach');
  parts.push('- [ ] Define dark mode / theme tokens');
  parts.push('- [ ] Add accessibility guidelines for each component');
  parts.push('- [ ] Create animation/transition token library');
  parts.push('- [ ] Document component composition patterns');
  parts.push('- [ ] Add code examples and integration guides');
  parts.push('- [ ] Establish naming conventions documentation');
  parts.push('- [ ] Create deprecation strategy for old components');
  parts.push('');

  return parts.join('\n');
}
