import type { RootManifest, ColorToken, TypographyToken, SpacingToken, GridToken, ComponentDoc } from '@/types/schemas';

export function renderMarkdown(manifest: RootManifest): string {
  const fileName = manifest.source.fileName;
  const generatedAt = manifest.generatedAt;
  const { foundations, components, health } = manifest.domains;

  const parts: string[] = [];

  parts.push(`# ${fileName} Design System`);
  parts.push(`> Generated by Documint · ${new Date(generatedAt).toLocaleDateString()}\n`);

  // Foundations
  parts.push('## Foundations\n');

  if (foundations.colors.length > 0) {
    parts.push(`### Colors (${foundations.colors.length})\n`);
    parts.push('| Name | Hex | Role | White BG | WCAG AA | WCAG AAA | Usage |');
    parts.push('|------|-----|------|----------|---------|----------|-------|');
    foundations.colors.forEach((color) => {
      const wcagAA = color.wcagAA ? '✓' : '✗';
      const wcagAAA = color.wcagAAA ? '✓' : '✗';
      parts.push(
        `| ${color.tokenName} | \`${color.value.hex}\` | ${color.semanticRole || '—'} | ${color.contrastOnWhite?.toFixed(2) || '—'} | ${wcagAA} | ${wcagAAA} | ${color.usageHint || '—'} |`
      );
    });
    parts.push('');
  }

  if (foundations.typography.length > 0) {
    parts.push(`### Typography (${foundations.typography.length})\n`);
    parts.push('| Name | Family | Weight | Size | Line Height | Role |');
    parts.push('|------|--------|--------|------|-------------|------|');
    foundations.typography.forEach((typo) => {
      parts.push(
        `| ${typo.tokenName} | ${typo.fontFamily} | ${typo.fontWeight} | ${typo.fontSize} | ${typo.lineHeight.value}${typo.lineHeight.unit} | ${typo.role || '—'} |`
      );
    });
    parts.push('');
  }

  if (foundations.spacing.length > 0) {
    parts.push(`### Spacing (${foundations.spacing.length})\n`);
    parts.push('| Name | Value | Scale Step | Usage |');
    parts.push('|------|-------|------------|-------|');
    foundations.spacing.forEach((spacing) => {
      parts.push(
        `| ${spacing.tokenName} | ${spacing.value}${spacing.unit} | ${spacing.scaleStep || '—'} | ${spacing.usageHint || '—'} |`
      );
    });
    parts.push('');
  }

  if (foundations.grids.length > 0) {
    parts.push(`### Grids (${foundations.grids.length})\n`);
    parts.push('| Name | Type | Columns | Gutter | Margin | Breakpoint |');
    parts.push('|------|------|---------|--------|--------|------------|');
    foundations.grids.forEach((grid) => {
      parts.push(
        `| ${grid.tokenName} | ${grid.type} | ${grid.count || '—'} | ${grid.gutter || '—'} | ${grid.margin || '—'} | ${grid.breakpointHint || '—'} |`
      );
    });
    parts.push('');
  }

  // Components
  if (components.components.length > 0) {
    parts.push(`## Components (${components.components.length})\n`);

    components.components.forEach((comp) => {
      parts.push(`### ${comp.name} · ${comp.category}\n`);

      if (comp.description) {
        parts.push(`${comp.description}\n`);
      }

      if (comp.states.length > 0 || comp.variantGroups.length > 0) {
        const stateStr = comp.states.length > 0 ? `**States:** ${comp.states.join(', ')}` : '';
        const variantStr =
          comp.variantGroups.length > 0 ? `**Variants:** ${comp.variantGroups.map((v) => v.property).join(', ')}` : '';
        parts.push([stateStr, variantStr].filter(Boolean).join(' | '));
        parts.push('');
      }

      if (comp.variants.length > 0) {
        parts.push('#### Variants\n');
        const variantCombos = comp.variants.map((v) =>
          Object.entries(v.combination)
            .map(([key, val]) => `${key}=${val}`)
            .join(', ')
        );
        const cols = Object.keys(comp.variants[0]?.combination || {});
        if (cols.length > 0) {
          parts.push(`| ${cols.join(' | ')} |`);
          parts.push(`| ${cols.map(() => '---').join(' | ')} |`);
          comp.variants.forEach((v) => {
            parts.push(`| ${Object.values(v.combination).join(' | ')} |`);
          });
        }
        parts.push('');
      }

      if (comp.tokenBindings && Object.values(comp.tokenBindings).some((arr) => arr.length > 0)) {
        parts.push('#### Token Bindings\n');
        const bindings = comp.tokenBindings;
        if (bindings.colors && bindings.colors.length > 0)
          parts.push(`- **Colors:** ${bindings.colors.map((pair) => pair[1]).join(', ')}`);
        if (bindings.typography && bindings.typography.length > 0)
          parts.push(`- **Typography:** ${bindings.typography.map((pair) => pair[1]).join(', ')}`);
        if (bindings.spacing && bindings.spacing.length > 0)
          parts.push(`- **Spacing:** ${bindings.spacing.map((pair) => pair[1]).join(', ')}`);
        if (bindings.effects && bindings.effects.length > 0)
          parts.push(`- **Effects:** ${bindings.effects.map((pair) => pair[1]).join(', ')}`);
        parts.push('');
      }

      if (comp.usageGuidelines) {
        parts.push('#### Usage Guidelines\n');
        if (comp.usageGuidelines.when) parts.push(`**When to use:** ${comp.usageGuidelines.when}`);
        if (comp.usageGuidelines.whenNot) parts.push(`**When not to use:** ${comp.usageGuidelines.whenNot}`);
        if (comp.usageGuidelines.antiPatterns && comp.usageGuidelines.antiPatterns.length > 0) {
          parts.push(`**Anti-patterns:**`);
          comp.usageGuidelines.antiPatterns.forEach((ap) => parts.push(`- ${ap}`));
        }
        parts.push('');
      }
    });
  }

  // Health Report
  parts.push('## Health Report\n');
  parts.push(`**Overall Score:** ${health.overallScore}/100\n`);

  parts.push('| Dimension | Score |');
  parts.push('|-----------|-------|');
  parts.push(`| Foundations | ${health.breakdown.foundationsScore} |`);
  parts.push(`| Components | ${health.breakdown.componentsScore} |`);
  parts.push(`| Token Coverage | ${health.breakdown.tokenCoverageScore} |`);
  parts.push(`| Naming Consistency | ${health.breakdown.namingConsistencyScore} |`);
  parts.push('');

  if (health.warnings.length > 0) {
    parts.push('### Warnings\n');
    parts.push('| Severity | Domain | Item | Message | Suggestion |');
    parts.push('|----------|--------|------|---------|-----------|');
    health.warnings.forEach((warning) => {
      parts.push(
        `| ${warning.severity} | ${warning.domain} | ${warning.itemName || '—'} | ${warning.message} | ${warning.suggestion || '—'} |`
      );
    });
  }

  return parts.join('\n');
}
